# Pandas

Pandas is a Python library that helps us **read, organize, clean, analyze, and summarize data**. It is commonly used when working with Excel files, CSV files, and datasets.

## What, Why, and Where?

- **What is Pandas?** A Python library for working with structured data in tables.
- **Why use it?** It makes filtering, cleaning, calculating, and summarizing data easier.
- **Where is it used?** Data analysis, business reports, dashboards, and machine-learning preparation.

## 1. Install and import Pandas

If Pandas is not installed, run `pip install pandas` in your terminal or notebook.

We usually import it using the short name `pd`.

In [2]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

## 2. Create your first Series

A **Series** is like one column in a table.

In [12]:
marks = pd.Series([85, 90, 78, 92])
print(marks)

# Print without index and dtype
print(marks.to_string(index=False))

0    85
1    90
2    78
3    92
dtype: int64
85
90
78
92

**Understand it:** Each value has an index (0, 1, 2, 3). Pandas creates these index labels automatically.

**Try it:** Create a Series containing five prices.

In [13]:
prices = pd.Series([120, 250, 80, 500, 175])
prices

0    120
1    250
2     80
3    500
4    175
dtype: int64

## 3. Create a DataFrame

A **DataFrame** is like a table with rows and columns.

In [36]:
data = {
    "Name": ["Anu", "Bala", "Charan", "Divya", "Ezhil"],
    "Age": [21, 22, 20, 23, 21],
    "City": ["Chennai", "Coimbatore", "Madurai", "Chennai", "Salem"],
    "Marks": [85, 72, 91, 66, 78],
    "Attendance": [92, 85, 96, 70, 88]
}

df = pd.DataFrame(data)
df

# print(df.to_string(index=False))

     Name  Age        City  Marks  Attendance
0     Anu   21     Chennai     85          92
1    Bala   22  Coimbatore     72          85
2  Charan   20     Madurai     91          96
3   Divya   23     Chennai     66          70
4   Ezhil   21       Salem     78          88

**What happened?** We made a table from a Python dictionary. Each dictionary key became a column name.

- **Row:** information about one student.
- **Column:** one type of information, such as `Marks`.
- **DataFrame:** the complete table.

## 4. View the data

These commands help you quickly understand a dataset.

In [8]:
print("First 3 rows:")
display(df.head(3))

print("Last 2 rows:")
display(df.tail(2))

print("Dataset size (rows, columns):", df.shape)
print("Column names:", df.columns.tolist())
print("Column data types:")
df.dtypes

First 3 rows:

     Name  Age        City  Marks  Attendance
0     Anu   21     Chennai     85          92
1    Bala   22  Coimbatore     72          85
2  Charan   20     Madurai     91          96

Last 2 rows:

    Name  Age     City  Marks  Attendance
3  Divya   23  Chennai     66          70
4  Ezhil   21    Salem     78          88

Dataset size (rows, columns): (5, 5)
Column names: ['Name', 'Age', 'City', 'Marks', 'Attendance']
Column data types:

Name          object
Age            int64
City          object
Marks          int64
Attendance     int64
dtype: object

- `head(n)` shows the first *n* rows.
- `tail(n)` shows the last *n* rows.
- `shape` gives `(number of rows, number of columns)`.
- `dtypes` shows the type of data in each column.

## 5. Select columns and rows

Use a column name to select one column. Use `loc` for label-based selection and `iloc` for position-based selection.

In [6]:
# One column (returns a Series)
df["Name"]

0       Anu
1      Bala
2    Charan
3     Divya
4     Ezhil
Name: Name, dtype: object

In [7]:
# Multiple columns (returns a DataFrame)
df[["Name", "Marks"]]

     Name  Marks
0     Anu     85
1    Bala     72
2  Charan     91
3   Divya     66
4   Ezhil     78

In [28]:
# Rows with index labels 0 and 1
df.loc[0]

Name              Anu
Age                21
City          Chennai
Marks              85
Attendance         92
Name: 0, dtype: object

In [9]:
# First two rows by position
df.iloc[1:2]

   Name  Age        City  Marks  Attendance
1  Bala   22  Coimbatore     72          85

**Remember:**
- `df["Marks"]` selects the Marks column.
- `df[["Name", "Marks"]]` selects two columns.
- `loc` uses index labels; `iloc` uses integer positions.
- Python slices usually exclude the ending position, but `loc[0:1]` includes label `1`.

## 6. Filter rows

Filtering means keeping only rows that match a condition.

In [14]:
# Students who scored at least 80
high_marks = df[df["Marks"] >= 80]
high_marks

     Name  Age     City  Marks  Attendance
0     Anu   21  Chennai     85          92
2  Charan   20  Madurai     91          96

In [15]:
# Students from Chennai
chennai_students = df[df["City"] == "Chennai"]
chennai_students

    Name  Age     City  Marks  Attendance
0    Anu   21  Chennai     85          92
3  Divya   23  Chennai     66          70

In [16]:
# Students with marks >= 80 AND attendance >= 90
df[(df["Marks"] >= 80) & (df["Attendance"] >= 90)]

     Name  Age     City  Marks  Attendance
0     Anu   21  Chennai     85          92
2  Charan   20  Madurai     91          96

**Tip:** Use `&` for AND and `|` for OR. Put each condition inside parentheses.

**Try it:** Show students whose marks are below 75.

## 7. Add, update, and remove columns

You can calculate a new column from existing columns.

In [28]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [29]:
df['Salary'] = [70000, 80000, 90000]
df

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30    London   80000
2  Charlie   35     Paris   90000

In [19]:
# Updating Columns

# # Increase all ages by 1
# df['Age'] = df['Age'] + 1

# Update 'City' to 'Remote' where Age is greater than 30
df.loc[df['Age'] > 30, 'City'] = 'Remote'
df
# Replace specific values
df['City'] = df['City'].replace({'New York': 'NYC'})
df

      Name  Age    City  Salary
0    Alice   25     NYC   70000
1      Bob   30  London   80000
2  Charlie   35  Remote   90000

In [32]:
#Removing Columns

# Drop a single column (must specify axis=1)
# df = df.drop('Salary', axis=1, errors='ignore')
# df
# # Drop multiple columns at once
# df = df.drop(columns=['City', 'Age'])
df

      Name
0    Alice
1      Bob
2  Charlie

## 8. Sort data

Sorting puts rows in order.

In [40]:
# Highest marks first
df.sort_values(by="Marks", ascending=False)

     Name  Age        City  Marks  Attendance
2  Charan   20     Madurai     91          96
0     Anu   21     Chennai     85          92
4   Ezhil   21       Salem     78          88
1    Bala   22  Coimbatore     72          85
3   Divya   23     Chennai     66          70

In [41]:
# City A–Z, then marks highest first within each city
df.sort_values(by=["City", "Marks"], ascending=[True, False])

     Name  Age        City  Marks  Attendance
0     Anu   21     Chennai     85          92
3   Divya   23     Chennai     66          70
1    Bala   22  Coimbatore     72          85
2  Charan   20     Madurai     91          96
4   Ezhil   21       Salem     78          88

## 9. Basic calculations and summary statistics

Pandas can quickly calculate totals, averages, minimums, and maximums.

In [42]:
print("Total marks:", df["Marks"].sum())
print("Average marks:", df["Marks"].mean())
print("Highest marks:", df["Marks"].max())
print("Lowest marks:", df["Marks"].min())
print("Median marks:", df["Marks"].median())

Total marks: 392
Average marks: 78.4
Highest marks: 91
Lowest marks: 66
Median marks: 78.0

In [37]:
# Summary of numeric columns
# df.describe()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   City        5 non-null      object
 3   Marks       5 non-null      int64
 4   Attendance  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes

- `sum()` adds values.
- `mean()` calculates the average.
- `median()` finds the middle value.
- `describe()` gives count, mean, standard deviation, minimum, quartiles, and maximum for numeric columns.

## 10. Count categories with `value_counts()`

This is useful for questions such as “How many students are from each city?”

In [44]:
df["City"].value_counts()

City
Chennai       2
Coimbatore    1
Madurai       1
Salem         1
Name: count, dtype: int64

## 11. Group data with `groupby()`

`groupby()` lets us summarize data by category—for example, average marks by city.

In [25]:
# Average marks for each city
df.groupby("City")["Marks"].mean().sort_values(ascending=False)

City
Madurai       91.0
Trichy        85.0
Salem         78.0
Coimbatore    72.0
Chennai       66.0
Name: Marks, dtype: float64

In [38]:
# Several summaries for each city
df.groupby("City").agg(
    Student_Count=("Name", "count"),
    Average_Marks=("Marks", "mean"),
    Highest_Marks=("Marks", "max")
).round(2)

            Student_Count  Average_Marks  Highest_Marks
City
Chennai                 2           75.5             85
Coimbatore              1           72.0             72
Madurai                 1           91.0             91
Salem                   1           78.0             78

**Simple idea:** Split rows into groups, calculate something for each group, and show the results.

## 12. Find missing values

Real datasets often contain empty cells. Pandas represents many missing values as `NaN`.

In [43]:
messy_data = pd.DataFrame({
    "Name": ["Arun", "Banu", "Cathy", "Dinesh"],
    "Age": [22, None, 21, 24],
    "Marks": [80, 75, None, 90],
    "City": ["Chennai", "Madurai", None, "Salem"]
})

messy_data

     Name   Age  Marks     City
0    Arun  22.0   80.0  Chennai
1    Banu   NaN   75.0  Madurai
2   Cathy  21.0    NaN     None
3  Dinesh  24.0   90.0    Salem

In [41]:
# Count missing values in each column
messy_data.isna().sum()

Name     0
Age      1
Marks    1
City     1
dtype: int64

### Ways to handle missing values

There is no single best solution. Choose based on what the data means.

In [44]:
# # Option A: remove rows that contain any missing value
# complete_rows = messy_data.dropna()
# display(complete_rows)

# Option B: fill missing numeric values with the column average
filled_data = messy_data.copy()
filled_data["Age"] = filled_data["Age"].fillna(filled_data["Age"].mean())
filled_data["Marks"] = filled_data["Marks"].fillna(filled_data["Marks"].mean())
filled_data["City"] = filled_data["City"].fillna("Unknown")
filled_data

     Name        Age      Marks     City
0    Arun  22.000000  80.000000  Chennai
1    Banu  22.333333  75.000000  Madurai
2   Cathy  21.000000  81.666667  Unknown
3  Dinesh  24.000000  90.000000    Salem

**Important:** Filling with an average or `"Unknown"` is only an example. Before cleaning real data, investigate why values are missing and choose a sensible approach.

## 13. Find and remove duplicate rows

In [46]:
duplicate_data = pd.DataFrame({
    "Name": ["Anu", "Bala", "Anu", "Charan"],
    "Marks": [85, 72, 85, 91]
})

print("Duplicate row flags based on Name and Marks:")
display(duplicate_data.duplicated(subset=['Name', 'Marks']))

# Remove duplicates looking at Name and Marks specifically
clean_duplicates = duplicate_data.drop_duplicates(subset=['Name', 'Marks'])

print("\nCleaned DataFrame:")
print(clean_duplicates)

Duplicate row flags based on Name and Marks:

0    False
1    False
2    False
3    False
dtype: bool

Cleaned DataFrame:
     Name  Marks
0     Anu     85
1    Bala     72
2     Anu     84
3  Charan     91

- `duplicated()` marks repeated rows as `True`.
- `drop_duplicates()` returns a DataFrame with duplicate rows removed.
- If only certain columns define a duplicate, use `drop_duplicates(subset=["Name"])`—but confirm that rule makes sense for your data.

## 14. Work with text

String methods help clean and search text values.

In [31]:
names_data = pd.DataFrame({
    "Name": [" anu ", "BALA", "charan ", "Divya"],
    "Department": [" data ", "HR", "DATA", "Finance"]
})

names_data["Name_Clean"] = names_data["Name"].str.strip().str.title()
names_data["Department_Clean"] = names_data["Department"].str.strip().str.upper()
names_data

      Name Department Name_Clean Department_Clean
0     anu       data         Anu             DATA
1     BALA         HR       Bala               HR
2  charan        DATA     Charan             DATA
3    Divya    Finance      Divya          FINANCE

- `str.strip()` removes extra spaces at the start and end.
- `str.title()` capitalizes words.
- `str.upper()` converts text to uppercase.

## 15. Read a CSV file

CSV files are common in data analytics. `read_csv()` loads one into a DataFrame.

In [53]:
# Create a small example CSV, then read it back.
sample_csv = pd.DataFrame({
    "Product": ["Pen", "Notebook", "Bag"],
    "Price": [10, 50, 600],
    "Quantity": [20, 12, 3]
})

sample_csv.to_csv("sample_sales.csv", index=False)
sales = pd.read_csv("sample_sales.csv")
sales

    Product  Price  Quantity
0       Pen     10        20
1  Notebook     50        12
2       Bag    600         3

**Using your own file:** put the CSV file in the notebook's working folder, then run:

`my_data = pd.read_csv("your_file.csv")`

If your file is elsewhere, provide its correct path. `index=False` prevents Pandas from saving the row index as an extra column.

## 16. Create calculated columns for analysis

Let's calculate revenue from price and quantity.

In [54]:
sales["Revenue"] = sales["Price"] * sales["Quantity"]
sales

    Product  Price  Quantity  Revenue
0       Pen     10        20      200
1  Notebook     50        12      600
2       Bag    600         3     1800

In [55]:
print("Total revenue:", sales["Revenue"].sum())
print("Average product price:", sales["Price"].mean())

Total revenue: 2600
Average product price: 220.0

This is a basic data-analysis pattern: create a meaningful metric, then summarize it.

## 17. Merge two DataFrames

A merge combines tables using a shared column, similar to a SQL join.

In [56]:
students = pd.DataFrame({
    "Student_ID": [1, 2, 3],
    "Name": ["Anu", "Bala", "Charan"]
})

scores = pd.DataFrame({
    "Student_ID": [1, 2, 3],
    "Marks": [85, 72, 91]
})

merged = pd.merge(students, scores, on="Student_ID", how="inner")
merged

   Student_ID    Name  Marks
0           1     Anu     85
1           2    Bala     72
2           3  Charan     91

- `on="Student_ID"` says which column matches.
- `how="inner"` keeps only IDs found in both tables.
- Other common options are `left`, `right`, and `outer`.

## 19. Mini project: Student performance analysis

Use the student dataset from earlier to answer common questions.

In [38]:
# 1. Display the dataset
display(df)

# 2. Average marks
average_marks = df["Marks"].mean()
print(f"Average marks: {average_marks:.2f}")

# 3. Students scoring 80 or more
display(df[df["Marks"] >= 80][["Name", "Marks"]])

# 4. Average attendance
print(f"Average attendance: {df['Attendance'].mean():.2f}%")

# 5. Average marks by city
display(df.groupby("City")["Marks"].mean().sort_values(ascending=False))

     Name  Age        City  Marks  Attendance Result  Bonus_Marks
0     Anu   21      Trichy     85          92   Pass           90
1    Bala   22  Coimbatore     72          85   Pass           77
2  Charan   20     Madurai     91          96   Pass           96
3   Divya   23     Chennai     66          70   Pass           71
4   Ezhil   21       Salem     78          88   Pass           83

Average marks: 78.40

     Name  Marks
0     Anu     85
2  Charan     91

Average attendance: 86.20%

City
Madurai       91.0
Trichy        85.0
Salem         78.0
Coimbatore    72.0
Chennai       66.0
Name: Marks, dtype: float64

In [59]:
# Sample Data
data = {
    'Region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'Product': ['Apples', 'Apples', 'Bananas', 'Bananas', 'Apples', 'Bananas'],
    'Sales': [100, 150, 200, 350, 120, 400]
}
df = pd.DataFrame(data)

# # Create basic pivot table (default calculation is mean)
# pivot = pd.pivot_table(df, values='Sales', index='Region', columns='Product')
# print(pivot)

pivot_sum = pd.pivot_table(
    df, 
    values='Sales', 
    index='Region', 
    columns='Product', 
    aggfunc='sum', 
    fill_value=0,
    margins=True,
    margins_name='ALL'# Adds the 'All' grand totals row/column
)
print(pivot_sum)

Product  Apples  Bananas   ALL
Region
East        220      200   420
West        150      750   900
ALL         370      950  1320

## Quick revision

| Task | Pandas code |
|---|---|
| Create a table | `pd.DataFrame(data)` |
| Read CSV | `pd.read_csv("file.csv")` |
| See first rows | `df.head()` |
| Check size | `df.shape` |
| Select a column | `df["Marks"]` |
| Filter rows | `df[df["Marks"] > 80]` |
| Sort rows | `df.sort_values("Marks")` |
| Average | `df["Marks"].mean()` |
| Count categories | `df["City"].value_counts()` |
| Group and summarize | `df.groupby("City")["Marks"].mean()` |
| Count missing values | `df.isna().sum()` |
| Remove duplicates | `df.drop_duplicates()` |
| Combine tables | `pd.merge(df1, df2, on="ID")` |
| Save CSV | `df.to_csv("output.csv", index=False)` |

In [65]:
demo = pd.read_excel("Sales_Data.xlsx")
demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         10000 non-null  object
 1   OrderDate       10000 non-null  datetime64[ns]
 2   CustomerName    10000 non-null  object
 3   Product         10000 non-null  object
 4   Category        10000 non-null  object
 5   Quantity        10000 non-null  int64
 6   SalesAmount     10000 non-null  int64
 7   CostPrice       10000 non-null  float64
 8   Profit          10000 non-null  float64
 9   Region          10000 non-null  object
 10  Segment         10000 non-null  object
 11  Team            10000 non-null  object
 12  SalesExecutive  10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 1015.8+ KB

In [64]:
demo.describe()

,OrderDate,Quantity,SalesAmount,CostPrice,Profit
count,10000,10000.0000,10000.000000,10000.000000,10000.000000
mean,2023-08-29 13:48:34.560000,5.5036,5640.228300,717.633490,1692.068490
min,2023-03-01 00:00:00,1.0000,53.000000,35.000000,15.900000
25%,2023-05-30 00:00:00,3.0000,1857.750000,372.400000,557.325000
50%,2023-08-28 00:00:00,5.0000,4448.500000,712.600000,1334.550000
75%,2023-12-01 00:00:00,8.0000,8379.250000,1064.000000,2513.775000
max,2024-02-29 00:00:00,10.0000,20000.000000,1400.000000,6000.000000
std,NaN,2.8451,4544.442023,395.813863,1363.332607